# config/database.yml
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary:
    adapter: sqlite3
    database: db/development.sqlite3
  cable:
    adapter: sqlite3
    database: db/development.sqlite3
  queue:
    adapter: sqlite3
    database: db/development.sqlite3
  cache:            # optional, falls solid_cache im Gemfile ist
    adapter: sqlite3
    database: db/development.sqlite3

test:
  primary:
    adapter: sqlite3
    database: db/test.sqlite3
  cable:
    adapter: sqlite3
    database: db/test.sqlite3
  queue:
    adapter: sqlite3
    database: db/test.sqlite3
  cache:            # optional
    adapter: sqlite3
    database: db/test.sqlite3

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  cable:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  queue:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  cache:            # optional
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
