# config/database.yml
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary:
    adapter: sqlite3
    database: db/development.sqlite3
  cable:
    adapter: sqlite3
    database: db/development.sqlite3

test:
  primary:
    adapter: sqlite3
    database: db/test.sqlite3
  cable:
    adapter: sqlite3
    database: db/test.sqlite3

production:
  # Heroku / Postgres
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  cable:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
